#! /bin/sh
docker network create --driver=bridge \
    --subnet=$1 \
     trei-net1 

docker network create --driver=bridge \
    --subnet=$2 \
     trei-net2 

docker network create --driver=bridge \
    --subnet=$3 \
     trei-net3

docker network create --driver=bridge \
    --subnet=$4 \
     trei-net4  
