#! /bin/sh
docker network create --driver=bridge \
    --subnet=$1/24 \
     trei-net1 

docker network create --driver=bridge \
    --subnet=$2/24 \
     trei-net2 

docker network create --driver=bridge \
    --subnet=$3/24 \
     trei-net3

docker network create --driver=bridge \
    --subnet=$4/24 \
     trei-net4  
