#! /bin/bash

CONT_NAME=trei_emul_$7

PARENT_DIR=/home/gazauto/work/emulator
PARENT_WORK_DIR=$PARENT_DIR/trei_emul_instances
WORK_DIR=$PARENT_WORK_DIR/$CONT_NAME

ip1=$1
ip1=${ip1::-3}
ip2=$2
ip2=${ip2::-3}
ip3=$3
ip3=${ip3::-3}
ip4=$4
ip4=${ip4::-3}
udp=$5
tcp=$6

if [ ! -e $WORK_DIR ]; then
  mkdir  $WORK_DIR
  mkdir  $WORK_DIR/tasks
  cp -Rp unimod_add_to_settings/* $WORK_DIR/
  sync
fi

echo Stop \'$CONT_NAME\'...
docker stop $CONT_NAME
echo Remove \'$CONT_NAME\'...
docker rm $CONT_NAME
echo Start \'$CONT_NAME\'...
docker run --privileged \
	--mount type=bind,source=$WORK_DIR,target=/unimod_settings \
	--cpuset-cpus="0-1" \
	-p $udp:5000/udp \
	-p $tcp:6000/tcp \
	--network trei-net1 --ip=$ip1 \
	--name $CONT_NAME \
	-itd trei_emul

docker network connect trei-net2 --ip=$ip2 $CONT_NAME
docker network connect trei-net3 --ip=$ip3 $CONT_NAME
docker network connect trei-net4 --ip=$ip4 $CONT_NAME
echo Start \'$CONT_NAME\'. Done